version: '3.7'
services:
  redis-server:
    image: 'redis'
    command: redis-server --requirepass pass123 --appendonly yes
    volumes:
      - ./redis-data:/data
  fastapi-appointment:
    image: appointment-fastapi:latest
    build: .
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URI=postgresql://postgres:password@localhost/postgres
    network_mode: "host"  

    